#!/bin/bash
#SBATCH --job-name=TestSim
#SBATCH -p thin
#SBATCH -t 01:00:00
#SBATCH -N 1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=128
#SBATCH --mem=224000
#SBATCH -o number_density_band_TestSim.out
#SBATCH -e number_density_band_TestSim.err
#SBATCH -v
# SBATCH --exclusive

module purge

source $HOME/.conda/envs/neutrino_clustering/bin/activate

python $HOME/neutrino_clustering_V2/simulation_analytical.py \
-d L025N752/DMONLY/SigmaConstant00 \
--MW_halo \
--no-VC_halo \
--no-AG_halo