#!/bin/bash
#SBATCH --job-name=Sphere
#SBATCH -p fat
#SBATCH -t :00:00
#SBATCH -N 1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=128
#SBATCH --mem=960000
#SBATCH -o jobs/number_density_sphere_6shells.out
#SBATCH -e jobs/number_density_sphere_6shells.err
#SBATCH -v
#SBATCH --exclusive

module purge

source $HOME/.conda/envs/neutrino_clustering/bin/activate

python $HOME/neutrino_clustering_V2/number_density_sphere.py